# Generated by Django 6.0.2 on 2026-03-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_notification_action_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action_data',
            field=models.JSONField(blank=True, default=dict, help_text='Deep-link payload for mobile (e.g. screen + ids). Mirrored on push; use string values.'),
        ),
    ]
