# Generated by Django 6.0.2 on 2026-02-20 13:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('photo', models.ImageField(blank=True, upload_to='visits/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('distance_from_farmer', models.FloatField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('verified', 'Verified'), ('rejected', 'Rejected')], default='verified', max_length=20)),
                ('activity_type', models.CharField(choices=[('order_collection', 'Order collection'), ('debt_collections', 'Debt collections'), ('account_opening', 'Account opening'), ('farm_to_farm_visits', 'Farm to farm visits'), ('key_farm_visits', 'Key farm visits'), ('group_training', 'Group training'), ('common_interest_group_training', 'Common Interest Group training'), ('stakeholder_group_training', 'Stakeholder group training'), ('exhibition', 'Exhibition'), ('market_day_activation', 'Market day activation'), ('market_survey', 'Market survey'), ('competition_intelligence', 'Competition intelligence gathering'), ('reporting', 'Reporting'), ('demo_set_up', 'Demo set up'), ('spot_demo', 'Spot demo'), ('demo_site_training', 'Demo site training'), ('stakeholder_engagement', 'Stakeholder engagement'), ('farmers_cooperative_engagement', 'Farmers Cooperative society engagement'), ('stockists_activation', 'Stockists activation'), ('merchandising', 'Merchandising'), ('route_storming', 'Route storming'), ('farming_pocket_storming', 'Farming pocket storming'), ('counter_staff_training', 'Counter staff training'), ('counter_staff_bonding', 'Counter staff bonding session'), ('key_farmers_bonding', 'Key Farmers bonding session / Goat eating sessions')], default='farm_to_farm_visits', max_length=50)),
                ('crop_stage', models.CharField(blank=True, max_length=100)),
                ('germination_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('survival_rate', models.CharField(blank=True, max_length=50)),
                ('pests_diseases', models.CharField(blank=True, max_length=255)),
                ('order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('harvest_kgs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('farmers_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='farmers.farm')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='farmers.farmer')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
