# Generated by Django 6.0.2 on 2026-02-21 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_visit_officer_created_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['-created_at']},
        ),
    ]
