# Generated by Django

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
        ('visits', '0004_visit_is_deleted_visit_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='schedule',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='visits',
                to='schedules.schedule',
            ),
        ),
    ]
