# Generated by Django 6.0.2 on 2026-03-13 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0012_visit_verification_pending_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='farmers_feedback',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='visit',
            name='notes',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
    ]
