# Generated by Django 6.0.2 on 2026-03-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0019_seed_stockists_visit_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytypeconfig',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this activity from record-visit; existing visits remain unaffected.'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='activity_type',
            field=models.CharField(default='farm_to_farm_visits', help_text='Primary activity (first in activity_types) for reporting.', max_length=50),
        ),
        migrations.AlterField(
            model_name='visit',
            name='activity_types',
            field=models.JSONField(blank=True, default=list, help_text='List of activity type slugs performed in this visit. activity_type is the first (primary).'),
        ),
    ]
