# Generated by Django 6.0.3 on 2026-03-19 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_add_visit_route_fk'),
        ('visits', '0024_replace_product_focus_with_product_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='route',
            field=models.ForeignKey(blank=True, help_text='When set, this visit was recorded as part of this route (day plan).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='routes.route'),
        ),
    ]
