"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

import dj_database_url
from decouple import config

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = config("SECRET_KEY", default="django-insecure-dev-key-change-me")
DEBUG = config("DEBUG", default=True, cast=bool)
ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="localhost,127.0.0.1").split(",")

# DigitalOcean Spaces (S3-compatible API). django-storages/boto3 still use AWS_* setting names.
_DO_SPACES_BUCKET = (
    config("DO_SPACES_BUCKET_NAME", default="").strip()
    or config("AWS_STORAGE_BUCKET_NAME", default="").strip()
)
USE_DO_SPACES = _DO_SPACES_BUCKET != ""

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    "accounts",
    "farmers",
    "visits",
    "schedules",
    "routes",
    "notifications",
    "locations",
    "tracking",
    "site_config",
]
if USE_DO_SPACES:
    INSTALLED_APPS.append("storages")

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"
WSGI_APPLICATION = "config.wsgi.application"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# Database: use DATABASE_URL if set (PostgreSQL), else SQLite
_db_url = config("DATABASE_URL", default="")
if _db_url:
    DATABASES = {"default": dj_database_url.parse(_db_url)}
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

AUTH_USER_MODEL = "accounts.User"

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

LANGUAGE_CODE = "en-us"
TIME_ZONE = "Africa/Nairobi"
USE_I18N = True
USE_TZ = True

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media / uploads: DigitalOcean Spaces when bucket is configured, else local filesystem (dev).
if USE_DO_SPACES:
    AWS_ACCESS_KEY_ID = (
        config("DO_SPACES_ACCESS_KEY_ID", default="").strip()
        or config("AWS_ACCESS_KEY_ID", default="")
    )
    AWS_SECRET_ACCESS_KEY = (
        config("DO_SPACES_SECRET_ACCESS_KEY", default="").strip()
        or config("AWS_SECRET_ACCESS_KEY", default="")
    )
    AWS_STORAGE_BUCKET_NAME = _DO_SPACES_BUCKET
    # Spaces datacenter slug in hostname (e.g. fra1).
    AWS_S3_REGION_NAME = (
        config("DO_SPACES_REGION", default="").strip()
        or config("AWS_S3_REGION_NAME", default="fra1")
    )
    AWS_S3_OBJECT_PARAMETERS = {"CacheControl": "max-age=86400"}
    # django-storages defaults to presigned URLs when no custom_domain is set. Those expire
    # (AWS_QUERYSTRING_EXPIRE, default 3600s) while mobile/web cache API payloads → broken images.
    # False = stable object URLs; Space/bucket (or CDN in front) must allow anonymous GET for media keys.
    # Set AWS_QUERYSTRING_AUTH=true only if objects are private and you refresh URLs on every read.
    AWS_QUERYSTRING_AUTH = config(
        "AWS_QUERYSTRING_AUTH",
        default="false",
        cast=lambda v: str(v).strip().lower() in ("1", "true", "yes", "on"),
    )
    # Object key prefix inside the bucket (e.g. all uploads under media/…)
    _media_prefix = (
        config("DO_SPACES_MEDIA_PREFIX", default="").strip().strip("/")
        or config("AWS_S3_LOCATION", default="media").strip().strip("/")
        or "media"
    )
    AWS_LOCATION = _media_prefix
    # Recommended with modern buckets (ACLs disabled / bucket-owner enforced)
    AWS_DEFAULT_ACL = None
    _spaces_endpoint = (
        config("DO_SPACES_ENDPOINT_URL", default="").strip()
        or config("AWS_S3_ENDPOINT_URL", default="").strip()
    )
    AWS_S3_ENDPOINT_URL = _spaces_endpoint or (
        f"https://{AWS_S3_REGION_NAME}.digitaloceanspaces.com"
    )
    # Optional: CDN hostname without scheme (e.g. bucket.fra1.cdn.digitaloceanspaces.com)
    _spaces_cdn = (
        config("DO_SPACES_CDN_DOMAIN", default="").strip()
        or config("AWS_S3_CUSTOM_DOMAIN", default="").strip()
    )
    if _spaces_cdn:
        AWS_S3_CUSTOM_DOMAIN = _spaces_cdn
        MEDIA_URL = f"https://{_spaces_cdn}/{AWS_LOCATION}/"
    else:
        # Origin-style URL; keys are still prefixed with AWS_LOCATION by the storage backend.
        MEDIA_URL = (
            f"https://{AWS_STORAGE_BUCKET_NAME}.{AWS_S3_REGION_NAME}.digitaloceanspaces.com/{AWS_LOCATION}/"
        )
    STORAGES = {
        "default": {"BACKEND": "storages.backends.s3boto3.S3Boto3Storage"},
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
    }
else:
    MEDIA_URL = "media/"
    MEDIA_ROOT = BASE_DIR / "media"
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
            "OPTIONS": {
                "location": str(BASE_DIR / "media"),
                "base_url": "/media/",
            },
        },
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
    }

# DRF
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "accounts.authentication.SingleDeviceJWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    # Keep users signed in for up to one month (single-device policy still enforced).
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
}

# CORS
CORS_ALLOWED_ORIGINS = config(
    "CORS_ALLOWED_ORIGINS", default="http://localhost:3000,http://192.168.0.103:3000"
).split(",")
CORS_ALLOW_ALL_ORIGINS = True if DEBUG else False

# Visit photo: allowed MIME types (max size is in site_config DB)
VISIT_PHOTO_ALLOWED_EXTENSIONS = ("image/jpeg", "image/png", "image/jpg")

# Email (staff credentials): console when DEBUG, else SMTP (override with EMAIL_BACKEND if needed)
if DEBUG:
    EMAIL_BACKEND = config(
        "EMAIL_BACKEND",
        default="django.core.mail.backends.console.EmailBackend",
    )
else:
    EMAIL_BACKEND = config(
        "EMAIL_BACKEND",
        default="django.core.mail.backends.smtp.EmailBackend",
    )
EMAIL_HOST = config("SMTP_HOST", default="us2.smtp.mailhostbox.com")
EMAIL_PORT = config("SMTP_PORT", default=587, cast=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
EMAIL_USE_SSL = config("EMAIL_USE_SSL", default=False, cast=bool)
EMAIL_HOST_USER = config("SMTP_USER", default="no_reply@dancoon.tech")
# SMTP_PASS is required for SMTP authentication
# Set it via environment variable: export SMTP_PASS="your_password"
EMAIL_HOST_PASSWORD = config("SMTP_PASS", default="")
EMAIL_TIMEOUT = config("EMAIL_TIMEOUT", default=30, cast=int)  # Connection timeout in seconds (increased from 10 to 30)
DEFAULT_FROM_EMAIL = config("NOTIFICATION_PROVIDER_FROM", default="no_reply@dancoon.tech")
SERVER_EMAIL = config("SERVER_EMAIL", default=DEFAULT_FROM_EMAIL)

# Outbound email: optional Next.js internal API (Nodemailer). If WEB_MAIL_API_URL is set,
# Django POSTs there first; on failure or if unset, Django uses EMAIL_* / SMTP below.
WEB_MAIL_API_URL = config(
    "WEB_MAIL_API_URL",
    default="",
)
WEB_MAIL_INTERNAL_SECRET = config("WEB_MAIL_INTERNAL_SECRET", default="")
WEB_MAIL_REQUEST_TIMEOUT = config("WEB_MAIL_REQUEST_TIMEOUT", default=30, cast=int)

# Notifications: SMS backend (console = log only; twilio = notifications.sms_backends.TwilioSMSBackend)
NOTIFICATION_SMS_BACKEND = config(
    "NOTIFICATION_SMS_BACKEND",
    default="notifications.sms_backends.ConsoleSMSBackend",
)
# Twilio (optional): TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN, TWILIO_FROM_NUMBER
TWILIO_ACCOUNT_SID = config("TWILIO_ACCOUNT_SID", default="")
TWILIO_AUTH_TOKEN = config("TWILIO_AUTH_TOKEN", default="")
TWILIO_FROM_NUMBER = config("TWILIO_FROM_NUMBER", default="")

# Logging: console with level from LOG_LEVEL (default INFO). Per-app loggers available.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} [{levelname}] {name}: {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": config("LOG_LEVEL", default="INFO"),
    },
    "loggers": {
        "django": {"level": "INFO", "propagate": False},
        "django.request": {"level": "WARNING", "propagate": False},
        "accounts": {"level": "DEBUG", "propagate": True},
        "farmers": {"level": "DEBUG", "propagate": True},
        "visits": {"level": "DEBUG", "propagate": True},
        "schedules": {"level": "DEBUG", "propagate": True},
        "notifications": {"level": "DEBUG", "propagate": True},
        "locations": {"level": "DEBUG", "propagate": True},
        "mobile_sync": {"level": "DEBUG", "propagate": True},
    },
}
