# Generated by Django 6.0.2 on 2026-03-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_device_integrity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the server saved this record (can be later than capture if synced from offline).', verbose_name='Received (server)'),
        ),
        migrations.AlterField(
            model_name='locationreport',
            name='reported_at',
            field=models.DateTimeField(help_text='Device time when the location was captured by the phone (even when offline; synced later).', verbose_name='Captured (device time)'),
        ),
        migrations.AlterField(
            model_name='trackingsettings',
            name='interval_minutes',
            field=models.PositiveSmallIntegerField(default=1, help_text='Minutes between location reports during working hours (e.g. 1 = every minute).'),
        ),
    ]
