# Generated by Django 6.0.2 on 2026-02-21 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_schedule_officer_date_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['-scheduled_date', '-created_at']},
        ),
    ]
