# Generated by Django 6.0.2

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0005_alter_farmer_options"),
        ("schedules", "0004_schedule_is_deleted_schedule_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="farm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="farmers.farm",
            ),
        ),
    ]
