# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0005_schedule_farm"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="rejection_reason",
            field=models.TextField(
                blank=True,
                help_text="Reason given by supervisor/admin when rejecting a proposed schedule.",
            ),
        ),
    ]
