# Generated by Django 6.0.2 on 2026-03-13 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_schedule_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='notes',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason given by supervisor/admin when rejecting a proposed schedule.', validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
    ]
