# Generated by Django 6.0.3 on 2026-03-19 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0007_alter_schedule_notes_alter_schedule_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='edit_reason',
            field=models.TextField(blank=True, help_text='Reason given by the officer when requesting a change; schedule returns to proposed for supervisor approval.', validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
    ]
