# Generated by Django 6.0.3 on 2026-03-19 07:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0009_remove_farm_crop_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField(help_text='Day this route is planned for (e.g. Monday).')),
                ('name', models.CharField(blank=True, help_text="Optional label e.g. 'Eastern circuit', 'Nairobi stockists'.", max_length=120)),
                ('activity_types', models.JSONField(blank=True, default=list, help_text='List of activity type slugs for this route (same for all stops).')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('officer', models.ForeignKey(limit_choices_to={'role': 'officer'}, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_data', models.JSONField(blank=True, default=dict, help_text='Structured report content (e.g. summary, aggregated visit fields).')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='routes.route')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_route_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Order of this stop in the route (0 = first).')),
                ('farm', models.ForeignKey(blank=True, help_text='Optional specific farm/outlet for this stop.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_stops', to='farmers.farm')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='farmers.farmer')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='routes.route')),
            ],
            options={
                'ordering': ['route', 'order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['officer', '-scheduled_date'], name='route_officer_date'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('officer', 'scheduled_date'), name='route_officer_date_unique'),
        ),
        migrations.AddIndex(
            model_name='routestop',
            index=models.Index(fields=['route'], name='routestop_route_id'),
        ),
    ]
