# Generated by Django 6.0.3 on 2026-03-19 07:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_add_route_routestop_routereport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='route',
            name='route_officer_date_unique',
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('officer', 'scheduled_date'), name='route_officer_date_unique'),
        ),
    ]
