# Generated by Django 6.0.2 on 2026-03-19 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_add_visit_route_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routereport',
            name='report_data',
            field=models.JSONField(blank=True, default=dict, help_text='Structured report content derived from or summarizing farm activities recorded on visits during this route (e.g. aggregates, narrative summary).'),
        ),
        migrations.AlterField(
            model_name='routereport',
            name='route',
            field=models.OneToOneField(help_text='The route this report describes; content should align with visits/activities on that route.', on_delete=django.db.models.deletion.CASCADE, related_name='report', to='routes.route'),
        ),
    ]
