# Generated by Django 6.0.2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="County",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80)),
                ("region", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="counties", to="locations.region")),
            ],
            options={"ordering": ["name"], "unique_together": {("region", "name")}},
        ),
        migrations.CreateModel(
            name="SubCounty",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80)),
                ("county", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sub_counties", to="locations.county")),
            ],
            options={"ordering": ["name"], "unique_together": {("county", "name")}, "verbose_name_plural": "Sub-counties"},
        ),
    ]
