import { StyleSheet } from 'react-native';
import { colors, radius, spacing } from '@/constants/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1 },
  snackbarWrapper: { position: 'absolute', left: 0, right: 0 },
  snackbarTop: { marginHorizontal: 0 },
  snackbarGreen: { backgroundColor: colors.primary },
  container: { flex: 1 },
  scrollContent: { padding: spacing.lg, paddingBottom: spacing.xl },
  centered: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 24 },
  topBtn: { marginTop: 16 },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
    paddingBottom: spacing.xs,
  },
  headerLeft: { flex: 1 },
  headerStepLabel: { color: colors.gray500, marginBottom: 2 },
  headerTitle: { fontWeight: '700', color: colors.gray900 },
  headerClose: { padding: spacing.sm },
  headerCloseText: { fontSize: 28, lineHeight: 32, opacity: 0.85, color: colors.gray700 },
  offlineChip: { marginBottom: spacing.md },
  warningBox: {
    flexDirection: 'row',
    backgroundColor: colors.warningLight,
    borderRadius: radius.card,
    padding: spacing.lg,
    marginBottom: spacing.md,
    borderWidth: 1,
    borderColor: colors.warning,
  },
  warningBoxIcon: { marginRight: spacing.md },
  warningBoxContent: { flex: 1 },
  warningBoxTitle: { color: colors.warning, fontWeight: '600', marginBottom: 4 },
  warningBoxText: { color: colors.gray900 },
  nextBtnContent: { flexDirection: 'row-reverse' },
  section: {
    padding: spacing.lg,
    marginBottom: spacing.sm,
    borderRadius: radius.card,
    backgroundColor: colors.surfaceVariant,
  },
  locationBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.gray100,
    borderRadius: radius.card,
    padding: spacing.md,
  },
  locationBoxLeft: { flexDirection: 'row', alignItems: 'center', flex: 1 },
  locationIcon: { margin: 0, marginRight: spacing.md },
  locationStatus: { opacity: 0.85 },
  locationStatusError: { color: colors.error },
  photoEvidenceRow: { flexDirection: 'row', gap: spacing.md, marginBottom: spacing.md },
  photoEvidenceBtn: { flex: 1 },
  photoPreviewWrap: { marginTop: spacing.md, alignItems: 'center' },
  sectionTitle: { marginBottom: spacing.md },
  fieldLabel: { marginTop: spacing.xs, marginBottom: spacing.xs, fontWeight: '600', color: colors.gray700 },
  hint: { marginTop: spacing.xs, opacity: 0.85 },
  input: { marginBottom: spacing.md },
  inputHalf: { flex: 1, marginBottom: spacing.md },
  productFocusButton: { marginBottom: spacing.md },
  productLineCard: {
    borderWidth: 1,
    borderColor: colors.gray200,
    borderRadius: radius.md,
    padding: spacing.sm,
    marginBottom: spacing.sm,
  },
  productLineRow: { flexDirection: 'row', alignItems: 'flex-end', gap: spacing.sm, flexWrap: 'wrap' },
  productLineInput: { flex: 1, minWidth: 100 },
  productLineRemove: { marginBottom: 8 },
  twoColRow: { flexDirection: 'row', gap: spacing.md, marginBottom: 0 },
  addFarmerBtn: { marginTop: -2, marginBottom: 2 },
  farmList: { marginTop: spacing.xs },
  farmSelectWrap: { marginTop: spacing.sm },
  step2SectionTitle: {
    fontWeight: '600',
    color: colors.gray700,
    marginBottom: spacing.sm,
    marginTop: spacing.md,
    letterSpacing: 0.5,
  },
  farmerCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: radius.card,
    padding: spacing.lg,
    marginBottom: spacing.md,
    borderWidth: 1,
    borderColor: colors.gray200,
  },
  farmerCardAvatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: spacing.md,
  },
  farmerCardAvatarText: { color: colors.white, fontWeight: '700' },
  farmerCardBody: { flex: 1, minWidth: 0 },
  farmerCardName: { fontWeight: '700', color: colors.gray900 },
  farmerCardPhone: { flexDirection: 'row', alignItems: 'center', marginTop: 4, gap: 6 },
  farmerCardPhoneText: { color: colors.gray700 },
  farmerCardTag: { marginLeft: spacing.sm },
  activeChip: { backgroundColor: colors.primary },
  activeChipText: { color: colors.white, fontWeight: '600', fontSize: 12 },
  farmDisplay: {
    backgroundColor: colors.white,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.gray200,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    marginBottom: spacing.md,
  },
  farmSelectBtn: { marginBottom: 4 },
  farmSelectBtnContent: { justifyContent: 'flex-start' },
  muted: { opacity: 0.7 },
  farmerSelectBtn: { marginBottom: spacing.sm },
  farmerSelectBtnContent: { justifyContent: 'flex-start' },
  partnerTypeRow: { flexDirection: 'row', gap: 8, marginBottom: spacing.sm },
  partnerTypeBtn: { flex: 1 },
  partnerTypeHint: { marginBottom: spacing.sm, color: colors.gray700 },
  routeAdHocBtn: { marginTop: spacing.sm, alignSelf: 'flex-start' },
  skipPlanBtn: { alignSelf: 'flex-start' },
  step2Input: { marginBottom: spacing.md },
  locationCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.gray100,
    borderRadius: radius.card,
    padding: spacing.lg,
    marginBottom: spacing.lg,
    borderWidth: 1,
    borderColor: colors.gray200,
  },
  locationCardVerified: {
    backgroundColor: colors.primaryLight,
    borderColor: colors.primary,
  },
  locationCardLeft: { flexDirection: 'row', alignItems: 'center', flex: 1 },
  locationCardIcon: { marginRight: spacing.md },
  locationCardText: { flex: 1 },
  locationCardTitle: { fontWeight: '600', color: colors.gray700 },
  locationCardTitleVerified: { fontWeight: '600', color: colors.primary },
  locationCardDetail: { color: colors.gray700, marginTop: 2 },
  locationRefreshBtn: { padding: spacing.sm },
  photosRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginBottom: spacing.md, alignItems: 'flex-start' },
  photoThumbWrap: { position: 'relative' },
  photoThumb: { width: 80, height: 80, borderRadius: radius.sm },
  photoThumbRemove: { position: 'absolute', top: -4, right: -4, minWidth: 28, margin: 0 },
  photoAddBtn: {
    width: 80,
    height: 80,
    borderRadius: radius.sm,
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primaryLight + '40',
  },
  photoAddLabel: { marginTop: 4, color: colors.primary },
  photoPlaceholder: {
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: colors.gray200,
    borderRadius: radius.card,
    paddingVertical: spacing.xxl,
    paddingHorizontal: spacing.lg,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.md,
    backgroundColor: colors.gray100,
  },
  photoPlaceholderText: { color: colors.gray700, marginTop: spacing.md },
  photoPlaceholderHint: { color: colors.gray500, marginTop: spacing.xs },
  lockedHint: { marginTop: 2, marginBottom: 4 },
  errorHint: { marginTop: 4, marginBottom: 0 },
  scheduleChips: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginTop: spacing.sm },
  scheduleChip: { marginBottom: 0 },
  card: { marginBottom: spacing.md },
  divider: { marginVertical: spacing.xs },
  progressBar: { height: 6, borderRadius: radius.sm, marginVertical: spacing.xs },
  chip: { alignSelf: 'flex-start', marginTop: spacing.xs },
  locationLoading: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  locationLoadingText: { opacity: 0.8 },
  photoContent: { alignItems: 'center', overflow: 'hidden' },
  previewImg: { width: '100%', height: 200, borderRadius: radius.card, marginBottom: spacing.md },
  retakeBtn: { marginTop: spacing.xs },
  takePhotoBtn: { minWidth: 160 },
  cameraModal: { flex: 1, backgroundColor: '#000' },
  cameraModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 56,
    paddingBottom: 12,
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  cameraModalTitle: { color: '#fff' },
  cameraModalClose: { padding: 8 },
  cameraModalCloseText: { color: '#fff', fontSize: 32, lineHeight: 36 },
  cameraModalCamera: { flex: 1, position: 'relative' },
  cameraModalOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingBottom: 48,
  },
  captureButton: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderWidth: 4,
    borderColor: '#1B8F3A',
    justifyContent: 'center',
    alignItems: 'center',
  },
  captureButtonInner: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#fff',
  },
  cameraModalHint: { color: '#fff', marginTop: 12 },
  errorBlock: { marginVertical: 4 },
  actionsSection: { paddingTop: 12, paddingBottom: 4 },
  nextBtn: { marginBottom: 8 },
  submitBtn: { marginBottom: 0 },
  stepperRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.xl,
    paddingHorizontal: spacing.xs,
  },
  stepperItem: {
    alignItems: 'center',
    minWidth: 56,
  },
  stepperCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.gray200,
    justifyContent: 'center',
    alignItems: 'center',
  },
  stepperCircleActive: {
    backgroundColor: colors.primary,
  },
  stepperCircleText: { color: colors.gray500, fontWeight: '600' },
  stepperCircleTextActive: { color: colors.white, fontWeight: '600' },
  stepperLabel: { marginTop: 4, color: colors.gray500, fontSize: 12 },
  stepperLabelActive: { color: colors.primary, fontWeight: '600' },
  stepperLine: {
    flex: 1,
    height: 3,
    backgroundColor: colors.gray200,
    marginHorizontal: 4,
    marginBottom: 20,
    borderRadius: 2,
  },
  stepperLineActive: {
    backgroundColor: colors.primary,
  },
  stepActions: { flexDirection: 'row', gap: spacing.md, marginTop: spacing.md, marginBottom: spacing.lg },
  stepActionsWrap: { flexWrap: 'wrap' },
});
