# Generated by Django 6.0.2 on 2026-02-21 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
        ('locations', '0003_seed_subcounties_full'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='county',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='sub_county',
        ),
        migrations.AddField(
            model_name='farm',
            name='county_id',
            field=models.ForeignKey(blank=True, db_column='county_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locations.county'),
        ),
        migrations.AddField(
            model_name='farm',
            name='sub_county_id',
            field=models.ForeignKey(blank=True, db_column='sub_county_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locations.subcounty'),
        ),
    ]
