# Generated by Django 6.0.2 on 2026-02-21 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_remove_farm_county_remove_farm_sub_county_and_more'),
        ('locations', '0003_seed_subcounties_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='region_id',
            field=models.ForeignKey(blank=True, db_column='region_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locations.region'),
        ),
    ]
