# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0003_farm_region_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='title',
        ),
    ]
