# Generated by Django 6.0.2 on 2026-03-06 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0004_remove_farmer_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmer',
            options={'ordering': ['created_at']},
        ),
    ]
