# Generated by Django 6.0.2 on 2026-03-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0005_alter_farmer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='is_outlet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmer',
            name='is_stockist',
            field=models.BooleanField(default=False),
        ),
    ]
