# Generated by Django (remove Farmer.crop_type)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0006_farm_is_outlet_farmer_is_stockist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="farmer",
            name="crop_type",
        ),
    ]
