# Generated by Django 6.0.2 on 2026-03-13 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_user_current_refresh_jti'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_max_distance_meters', models.PositiveIntegerField(default=100, help_text='Max distance (m) from farmer/farm to accept a visit. Increase for dev/testing.')),
                ('visit_warning_distance_meters', models.PositiveIntegerField(default=80, help_text='Distance (m) at which mobile app shows a warning before user is over limit.')),
                ('visit_travel_validation_window_hours', models.FloatField(default=12.0, help_text='Only check travel speed if previous visit was within this many hours.')),
                ('visit_max_travel_speed_kmh', models.FloatField(default=120.0, help_text='Max reasonable speed (km/h) between consecutive visits; reject if exceeded.')),
                ('visit_photo_max_size_mb', models.PositiveSmallIntegerField(default=5, help_text='Max visit photo size in MB.')),
                ('partner_label', models.CharField(default='Farmer', help_text='Label for the person/entity (e.g. Farmer, Stockist, or Farmer / Stockist).', max_length=64)),
                ('location_label', models.CharField(default='Farm', help_text='Label for the location/plot (e.g. Farm, Outlet, or Farm / Outlet).', max_length=64)),
            ],
            options={
                'verbose_name': 'Site config',
                'verbose_name_plural': 'Site config',
            },
        ),
        migrations.CreateModel(
            name='DepartmentTerminology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_label', models.CharField(default='Farmer', help_text='Label for the person/entity (e.g. Farmer, Stockist).', max_length=64)),
                ('location_label', models.CharField(default='Farm', help_text='Label for the location/plot (e.g. Farm, Outlet).', max_length=64)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terminology', to='accounts.department')),
            ],
            options={
                'verbose_name': 'Department terminology',
                'verbose_name_plural': 'Department terminology',
            },
        ),
    ]
