# Generated by Django 6.0.2 on 2026-03-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0005_alter_siteconfig_location_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentterminology',
            name='location_label',
            field=models.CharField(default='Farm', help_text="Label for the location/plot. Use 'Farm', 'Outlet', or 'Farm / Outlet' for departments that have both.", max_length=64),
        ),
        migrations.AlterField(
            model_name='departmentterminology',
            name='partner_label',
            field=models.CharField(default='Farmer', help_text="Label for the person/entity. Use 'Farmer', 'Stockist', or 'Farmer / Stockist' for departments that have both (e.g. Mazao na afya).", max_length=64),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='location_label',
            field=models.CharField(default='Farm', help_text='Label for the location/plot (e.g. Farm, Outlet, or Farm / Outlet).', max_length=64),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='partner_label',
            field=models.CharField(default='Farmer', help_text='Label for the person/entity (e.g. Farmer, Stockist, or Farmer / Stockist).', max_length=64),
        ),
    ]
